fix: ImportError: sys.meta_path is None, Python is likely shutting down
    [12:33:15.058468][stream.segmented][debug] Closing worker thread
    [12:33:15.058616][stream.segmented][debug] Closing writer thread
    [12:33:15.058785][plugins.eplus][debug] [EplusSessionUpdater] Closing...
    [12:33:15.059220][plugins.eplus][debug] [EplusSessionUpdater] Closing...
    [12:33:15.060285][cli][info] Stream ended
    [12:33:15.060402][cli][info] Closing currently open stream...
    [12:33:15.060482][plugins.eplus][debug] [EplusSessionUpdater] Closing...
    --- Logging error ---
    Traceback (most recent call last):
    File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
        msg = self.format(record)
    File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
        return fmt.format(record)
    File "/usr/local/lib/python3.8/dist-packages/streamlink/logger.py", line 83, in format
        return super().format(record)
    File "/usr/lib/python3.8/logging/__init__.py", line 670, in format
        record.asctime = self.formatTime(record, self.datefmt)
    File "/usr/local/lib/python3.8/dist-packages/streamlink/logger.py", line 70, in formatTime
        return tdt.strftime(datefmt or self.default_time_format)
    ImportError: sys.meta_path is None, Python is likely shutting down
    Call stack:
    File ".../eplus.py", line 174, in close
        self.session_updater.close()
    File ".../eplus.py", line 59, in close
        log.debug('[EplusSessionUpdater] Closing...')
    Message: '[EplusSessionUpdater] Closing...'
    Arguments: ()